server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Toutes les requêtes qui ne trouvent pas de fichier physique 
    # sont redirigées vers index.html (Nécessaire pour React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour les assets statiques (images, css, js)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}
